'use client';

import { motion } from 'framer-motion';
import {
  FileText,
  Layers,
  Database,
  GitBranch,
  Boxes,
  Terminal,
  ArrowLeft,
  HardDrive,
} from 'lucide-react';
import type { AnalysisData } from '@/lib/types';

interface DashboardProps {
  data: AnalysisData;
  onReset: () => void;
}

const METRIC_ICONS = [Database, GitBranch, Boxes, Layers];

const CATEGORY_COLORS: Record<string, string> = {
  language: 'border-blue-500/30 bg-blue-500/5 text-blue-400',
  framework: 'border-violet-500/30 bg-violet-500/5 text-violet-400',
  database: 'border-emerald-500/30 bg-emerald-500/5 text-emerald-400',
  tooling: 'border-amber-500/30 bg-amber-500/5 text-amber-400',
  runtime: 'border-cyan-500/30 bg-cyan-500/5 text-cyan-400',
  library: 'border-zinc-700/50 bg-zinc-800/50 text-zinc-300',
};

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export function Dashboard({ data, onReset }: DashboardProps) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
      className="mx-auto w-full max-w-5xl px-6 pb-24 pt-28"
    >
      <div className="mb-8 flex items-center justify-between">
        <button
          onClick={onReset}
          className="inline-flex items-center gap-2 text-sm text-zinc-400 transition-colors hover:text-zinc-200"
        >
          <ArrowLeft className="h-4 w-4" />
          New Analysis
        </button>
        <div className="flex items-center gap-4 text-xs text-zinc-500">
          <span className="inline-flex items-center gap-1.5">
            <HardDrive className="h-3.5 w-3.5" />
            {formatFileSize(data.fileSize)}
          </span>
          <span className="inline-flex items-center gap-1.5">
            <FileText className="h-3.5 w-3.5" />
            {data.fileName}
          </span>
        </div>
      </div>

      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 }}
        className="mb-2"
      >
        <div className="mb-4 flex items-center gap-2.5">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg border border-violet-500/30 bg-violet-500/10">
            <Terminal className="h-4 w-4 text-violet-400" />
          </div>
          <div>
            <h1 className="font-sans text-2xl font-medium tracking-tight text-zinc-100">
              Analysis Report
            </h1>
            <p className="text-xs text-zinc-500">
              Generated by IBM Bob Enterprise Agent
            </p>
          </div>
        </div>
      </motion.div>

      <div className="grid gap-6">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.15 }}
          className="rounded-2xl border border-zinc-800 bg-zinc-900/30 p-7 backdrop-blur-md"
        >
          <div className="mb-4 flex items-center justify-between">
            <h2 className="font-sans text-sm font-medium tracking-tight text-zinc-300">
              Project Summary
            </h2>
            <span className="inline-flex items-center gap-1.5 rounded-full border border-violet-500/20 bg-violet-500/5 px-2.5 py-1 text-xs text-violet-400">
              <span className="h-1.5 w-1.5 rounded-full bg-violet-400" />
              IBM Bob
            </span>
          </div>
          <p className="text-base leading-relaxed text-zinc-400">
            {data.summary}
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="rounded-2xl border border-zinc-800 bg-zinc-900/30 p-7 backdrop-blur-md"
        >
          <h2 className="mb-5 font-sans text-sm font-medium tracking-tight text-zinc-300">
            Tech Stack Breakdown
          </h2>
          <div className="flex flex-wrap gap-2.5">
            {data.techStack.map((tech, idx) => (
              <motion.span
                key={`${tech.name}-${idx}`}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.3, delay: 0.25 + idx * 0.03 }}
                className={`inline-flex items-center rounded-full border px-3.5 py-1.5 text-xs font-medium ${
                  CATEGORY_COLORS[tech.category] || CATEGORY_COLORS.library
                }`}
              >
                {tech.name}
              </motion.span>
            ))}
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.25 }}
        >
          <h2 className="mb-5 font-sans text-sm font-medium tracking-tight text-zinc-300">
            Architecture & Metrics
          </h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {data.architecture.map((metric, idx) => {
              const Icon = METRIC_ICONS[idx % METRIC_ICONS.length];
              return (
                <motion.div
                  key={`${metric.label}-${idx}`}
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: 0.3 + idx * 0.08 }}
                  className="rounded-xl border border-zinc-800 bg-zinc-900/30 p-5 backdrop-blur-md transition-colors hover:border-zinc-700"
                >
                  <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg border border-zinc-800 bg-zinc-900">
                    <Icon className="h-4 w-4 text-violet-400" />
                  </div>
                  <p className="mb-1 text-xs text-zinc-500">{metric.label}</p>
                  <p className="font-sans text-sm font-medium tracking-tight text-zinc-200">
                    {metric.value}
                  </p>
                  {metric.description && (
                    <p className="mt-2 text-xs leading-relaxed text-zinc-600">
                      {metric.description}
                    </p>
                  )}
                </motion.div>
              );
            })}
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.35 }}
          className="rounded-2xl border border-zinc-800 bg-zinc-900/30 p-7 backdrop-blur-md"
        >
          <div className="mb-4 flex items-center justify-between">
            <h2 className="font-sans text-sm font-medium tracking-tight text-zinc-300">
              File Structure
            </h2>
            <Terminal className="h-4 w-4 text-zinc-600" />
          </div>
          <pre className="overflow-x-auto rounded-xl border border-zinc-800/60 bg-zinc-950/50 p-5 font-mono text-xs leading-relaxed text-zinc-400">
            {data.fileTree}
          </pre>
        </motion.div>
      </div>
    </motion.div>
  );
}
